notifications:
  email: false

language: python

branches:
  only:
    master

matrix:
  include:
    - env: TOX_ENV=py27-beets_master
      python: 2.7
    - env: TOX_ENV=py27-beets_release
      python: 2.7
    - env: TOX_ENV=py36-beets_master
      python: 3.6
    - env: TOX_ENV=py36-beets_release
      python: 3.6
    - env: TOX_ENV=py36-flake8
      python: 3.6

install:
  - "pip install tox"
  - "[ ! -z $COVERAGE ] && pip install coveralls || true"

script: "tox -e $TOX_ENV"

after_success:
  - "[ ! -z $COVERAGE ] && coveralls || true"
