notifications:
  email: false

language: python

env:
  - TOX_ENV=py27-beets_master
  - TOX_ENV=py27-beets_release
  - TOX_ENV=py36-beets_master COVERAGE=1
  - TOX_ENV=py36-beets_release
  - TOX_ENV=py36-flake8

install:
  - "pip install tox"
  - "[ ! -z $COVERAGE ] && pip install coveralls || true"

script: "tox -e $TOX_ENV"

after_success:
  - "[ ! -z $COVERAGE ] && coveralls || true"
